subject: O NAS
title: Kim jesteśmy i co tworzymy?
description: >-
  Zakład Stolarski Wsół to rodzinna pracownia stolarska, która działa w
  miejscowości Konina, na terenie gminy Niedźwiedź w powiecie limanowskim
  (Małopolska). Od wielu lat tworzymy drzwi, okna i schody drewniane na wymiar,
  łącząc pasję do rzemiosła z nowoczesną obróbką CNC i sprawdzonymi
  technologiami montażu. Stosujemy tylko drewno z certyfikowanych źródeł,
  odporne na warunki atmosferyczne, a każdy projekt realizujemy z myślą o
  trwałości, funkcjonalności i estetyce. Oferujemy kompleksową obsługę – od
  projektu, przez produkcję, aż po montaż i serwis. Dlaczego klienci wybierają
  nas? Bo stolarka drewniana to inwestycja na lata, a my gwarantujemy jakość,
  terminowość i uczciwe ceny. Zapraszamy do współpracy klientów indywidualnych,
  inwestorów i deweloperów poszukujących niezawodnych rozwiązań stolarskich w
  Małopolsce.
button:
  text: Sprawdź nasze oferty
  path: /#oferta
image:
  src: >-
    https://res.cloudinary.com/drtuzu5rl/image/upload/v1759145825/4454094691e47ff13556f97f6ea89ffd_mzdi8h_vfyvpq.jpg
  alt: Zakład stolarski wsół
