subject: FAQ
title: Najczęściej zadawane pytania
description: >-
  Zastanawiasz się, ile kosztują drzwi drewniane, jak wygląda montaż schodów
  albo ile trwa realizacja zamówienia? W tym miejscu zebraliśmy odpowiedzi na
  najczęściej zadawane pytania naszych klientów z Małopolski. Dzięki temu szybko
  znajdziesz praktyczne informacje o ofercie Zakładu Stolarskiego Wsół z Koniny
  i dowiesz się, jak przebiega współpraca – od pierwszego kontaktu, aż po gotowy
  montaż drzwi, okien czy schodów drewnianych. Nasze FAQ pomoże Ci rozwiać
  najczęstsze wątpliwości i upewnić się, że wybierasz sprawdzonego partnera w
  stolarce drewnianej.
questions:
  - question: Jakie usługi stolarskie oferuje Zakład Stolarski Wsół?
    answer: >-
      Specjalizujemy się w produkcji drzwi, okien i schodów drewnianych na
      wymiar. Oferujemy także drzwi góralskie, precyzyjną obróbkę CNC oraz inne
      elementy stolarskie wykonywane indywidualnie pod zamówienie klienta.
      Dzięki nowoczesnym maszynom i doświadczeniu możemy realizować zarówno
      klasyczne projekty, jak i nietypowe zamówienia.
  - question: Na jakim obszarze działacie?
    answer: >-
      Nasz zakład stolarski znajduje się w miejscowości Konina (gm. Niedźwiedź,
      pow. limanowski, Małopolska). Nasze usługi stolarskie świadczymy na
      terenie całej Małopolski – realizujemy projekty dla klientów z Krakowa,
      Tarnowa, Nowego Sącza, Oświęcimia, Zakopanego, a także mniejszych
      miejscowości, takich jak Myślenice, Wieliczka, Wadowice czy Olkusz.
      Niezależnie od tego, gdzie mieszkasz – przygotujemy drzwi, okna i schody
      drewniane dopasowane do Twojego domu.
  - question: Ile kosztują drzwi, okna lub schody drewniane na wymiar?
    answer: >-
      Cena zależy od rodzaju drewna, wymiarów, wykończenia i zastosowanych okuć.
      Każde zamówienie wyceniamy indywidualnie – oferujemy darmową wycenę po
      kontakcie telefonicznym lub mailowym.
  - question: Jak długo trwa realizacja zamówienia stolarskiego?
    answer: >-
      Czas realizacji zależy od rodzaju projektu. Średnio produkcja i montaż
      drzwi drewnianych na wymiar trwa od 4 do 8 tygodni, a schodów drewnianych
      – od 6 do 10 tygodni. W przypadku prostszych elementów stolarskich i
      obróbki CNC czas wykonania może być krótszy.
  - question: Czy oferujecie montaż drzwi, okien i schodów?
    answer: >-
      Tak – zapewniamy kompleksową obsługę: pomiar, projekt, produkcję,
      transport oraz profesjonalny montaż. Dzięki temu klient otrzymuje gotowe
      rozwiązanie, dopasowane do domu czy mieszkania. Montaż wykonują
      doświadczeni fachowcy, co daje gwarancję solidności i bezpieczeństwa
      użytkowania.
  - question: Czy przygotowujecie projekty indywidualne?
    answer: >-
      Tak. Wykonujemy projekty stolarskie na zamówienie, dopasowane do wymagań
      klienta i architektury budynku. Możemy stworzyć zarówno klasyczne okna i
      drzwi drewniane, jak i nietypowe realizacje – np. drzwi góralskie z
      ręcznymi zdobieniami, elementy dekoracyjne czy wykończenia wnętrz z litego
      drewna.
