owner: TADEUSZ WSÓŁ
company: Zakład Stolarski
location: Konina (gm. Niedźwiedź / pow. limanowski / małopolska)
offer: Drzwi, okna i schody drewniane na wymiar.
description: >-
  Szukasz stolarza na terenie Małopolski? W Zakładzie Stolarskim Wsół tworzymy
  drzwi, okna i schody drewniane na wymiar, łącząc tradycyjne rzemiosło z
  nowoczesną technologią CNC. Oferujemy również drzwi góralskie i unikalne
  projekty drewniane dopasowane do Twojego domu. Każdy element wykonujemy
  solidnie, estetycznie i z dbałością o każdy detal.
button:
  text: Dowiedz się więcej
  path: /#o-nas
image:
  src: >-
    https://res.cloudinary.com/drtuzu5rl/image/upload/v1759145826/jean-baptiste-d-44Vp65XxXs4-unsplash_s5iemw_sq03ef.jpg
  alt: >-
    Zakład stolarski Wsół — produkcja okien, drzwi i schodów drewnianych
    (Konina/Małopolskie)
